language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -r dev-requirements.txt
  - pip install .
# command to run tests
script:
  - flake8 config=.flake8
  - pytest
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd $TRAVIS_BUILD_DIR
    git checkout $TRAVIS_BRANCH
    python docs/gen_examples.py
    git -c user.name='daft-bot' -c user.email='foreman.mackey+daft-bot@gmail.com' commit -m "updating examples [ci skip]"
    git push https://$GITHUB_USER_NAME:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG $TRAVIS_BRANCH
  fi


