language: python
python:
  - "3.6"
  - "3.7"
addons:
  apt:
    packages:
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - dvipng
# command to install dependencies
install:
  - pip install -r dev-requirements.txt
  - pip install .
# command to run tests
script:
  - flake8 config=.flake8
  - pytest
after_success: |
  echo $TRAVIS_PYTHON_VERSION
  if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ -n "$GITHUB_API_KEY" ] &&  [ "$TRAVIS_PYTHON_VERSION" = "3.7" ] ; then
    cd $TRAVIS_BUILD_DIR
    git checkout $TRAVIS_BRANCH
    python docs/gen_example.py
    git add _static/examples examples
    git -c user.name='daft-bot' -c user.email='foreman.mackey+daft-bot@gmail.com' commit -m "updating examples [ci skip]"
    git push https://$GITHUB_USER_NAME:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG $TRAVIS_BRANCH
  fi


